apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: wanderlust
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: bablu001/wanderlust-frontend-beta:v8.0  # ✅ Use the correct frontend image
          ports:
            - containerPort: 5173  # ✅ Assuming your frontend app listens on this port
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: wanderlust
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 5173  # ✅ Match the containerPort
      protocol: TCP
      nodePort: 31000
